In [1]:
include("designMatrix.jl")

designMatrixEphemeris

# designMatrixRed

In [2]:
toas = [1, 2]
F, FFreqs = designMatrixRed(toas, nMode=2);

In [3]:
F

2×4 Array{Float64,2}:
 -2.44929e-16  1.0  -4.89859e-16  1.0
 -4.89859e-16  1.0  -9.79717e-16  1.0

In [4]:
FFreqs

4-element Array{Float64,1}:
 1.0
 1.0
 2.0
 2.0

In [5]:
?designMatrixRed

search: designMatrixRed designMatrixChromatic designMatrixEphemeris



```
designMatrixRed(
    toas;
    nMode=30, 
    TSpan=Nothing, 
    logFreq=false
)
```

Construct an $N_{toas} × 2N_{mode}$ Fourier design matrix from Eq.(11) of Lentati et al, 2013  (https://arxiv.org/pdf/1210.3578.pdf)

# Arguments

  * `toas::Array`: vector of time of arrial series in seconds.
  * `nMode::Integer=30`: number of fourier coefficients to use.
  * `TSpan:Float64=Nothing`: option to some other Tspan.
  * `logFreq::Bool=false`: use log frequency spacing.

# Examples

```jldoctest
julia> toas = [1, 2]
julia> F, FFreqs = designMatrixRed(toas, nMode=2);
julia> F
2×4 Array{Float64,2}:
 -2.44929e-16  1.0  -4.89859e-16  1.0
 -4.89859e-16  1.0  -9.79717e-16  1.0
julia> FFreqs
4-element Array{Float64,1}:
 1.0
 1.0
 2.0
 2.0
```

# See also

[`designMatrixEnvelope`](@ref), [`designMatrixChromatic`](@ref), [`designMatrixDM`](@ref), [`designMatrixEphemeris`](@ref)


# designMatrixEnvelope

In [6]:
toas = [1, 1.015]*53000.0day
F, FFreqs = designMatrixEnvelope(toas, nMode=2)

([-8.66025403784421e-8 -5.000000000000305e-8 8.660254037844738e-8 -4.999999999999388e-8; -2.5859143257199664e-9 -1.492978332055928e-9 2.585914325720221e-9 -1.4929783320554873e-9], [1.4558583740973678e-8, 1.4558583740973678e-8, 2.9117167481947356e-8, 2.9117167481947356e-8])

In [7]:
F

2×4 Array{Float64,2}:
 -8.66025e-8  -5.0e-8      8.66025e-8  -5.0e-8    
 -2.58591e-9  -1.49298e-9  2.58591e-9  -1.49298e-9

In [8]:
FFreqs

4-element Array{Float64,1}:
 1.4558583740973678e-8
 1.4558583740973678e-8
 2.9117167481947356e-8
 2.9117167481947356e-8

In [9]:
?designMatrixEnvelope

search: designMatrixEnvelope



```
designMatrixEnvelope(
    toas;
    log10Amp=-7.0,
    log10Q=log10(300.0),
    t0=53000.0day,
    nMode=30, 
    TSpan=Nothing, 
    logFreq=false
)
```

Construct an $N_{toas} × 2N_{mode}$ Fourier design matrix with gaussian envelope.  Current normalization expresses DM signal as a deviation [seconds] at fref [MHz]

# Arguments

  * `toas::Array`: vector of time of arrial series in seconds.
  * `log10Amp::Float64=-7.0`: log10 of the amplitude [s].
  * `log10Q::Float64=log10(300.0)`: log10 of standard deviation of gaussian envelope [days].
  * `t0::Float64=53000.0day`: mean of gaussian envelope [s].
  * `nMode::Integer=30`: number of fourier coefficients to use.
  * `TSpan:Float64=Nothing`: option to some other Tspan.
  * `logFreq::Bool=false`: use log frequency spacing.

# Examples

```jldoctest
julia> toas = [1, 1.015]*53000.0day
julia> F, FFreqs = designMatrixEnvelope(toas, nMode=2);
julia> F
2×4 Array{Float64,2}:
 -8.66025e-8  -5.0e-8      8.66025e-8  -5.0e-8    
 -2.58591e-9  -1.49298e-9  2.58591e-9  -1.49298e-9
julia> FFreqs
4-element Array{Float64,1}:
 1.455858374097388e-8
 1.455858374097388e-8
 2.911716748194776e-8
 2.911716748194776e-8
```

# See also

[`designMatrixRed`](@ref), [`designMatrixChromatic`](@ref), [`designMatrixDM`](@ref), [`designMatrixEphemeris`](@ref)


# designMatrixChromatic

In [10]:
toas = [1, 2]
freqs = [3, 4]
F, FFreqs = designMatrixChromatic(toas, freqs, nMode=2)

([-1.161630405828265e-5 4.742716049382717e10 -2.32326081165653e-5 4.742716049382717e10; -7.3509424118819875e-6 1.500625e10 -1.4701884823763975e-5 1.500625e10], [1.0, 1.0, 2.0, 2.0])

In [11]:
F

2×4 Array{Float64,2}:
 -1.16163e-5  4.74272e10  -2.32326e-5  4.74272e10
 -7.35094e-6  1.50063e10  -1.47019e-5  1.50063e10

In [12]:
FFreqs

4-element Array{Float64,1}:
 1.0
 1.0
 2.0
 2.0

In [13]:
?designMatrixChromatic

search: designMatrixChromatic



```
designMatrixChromatic(
    toas,
    freqs;
    nMode=30, 
    TSpan=Nothing, 
    fRef=1400.0,
    index=4.0,
    logFreq=false
)
```

Construct an $N_{toas} × 2N_{mode}$ scattering-variation Fourier design matrix.  Current normalization expresses scattering signal as a deviation [seconds] at fRef [MHz]

# Arguments

  * `toas::Array`: vector of time of arrial series in seconds.
  * `freqs:Array`: radio frequencies of observations [MHz].
  * `nMode::Integer=30`: number of fourier coefficients to use.
  * `TSpan:Float64=Nothing`: option to some other Tspan.
  * `fRef:Float64=1400.0`: reference frequency [MHz].
  * `index::Float64=4.0`: index of chromatic effects.
  * `logFreq::Bool=false`: use log frequency spacing.

# Examples

```jldoctest
julia> toas = [1, 2]
julia> freqs = [3, 4]
julia> F, FFreqs = designMatrixChromatic(toas, freqs, nMode=2);
julia> F
2×4 Array{Float64,2}:
 -1.16163e-5  4.74272e10  -2.32326e-5  4.74272e10
 -7.35094e-6  1.50063e10  -1.47019e-5  1.50063e10
julia> FFreqs
4-element Array{Float64,1}:
 1.0
 1.0
 2.0
 2.0
```

# See also

[`designMatrixRed`](@ref), [`designMatrixEnvelope`](@ref), [`designMatrixDM`](@ref), [`designMatrixEphemeris`](@ref)


# designMatrixDM

In [14]:
toas = [1, 2]
freqs = [3, 4]
F, FFreqs = designMatrixDM(toas, freqs, nMode=2)

([-5.334017169619583e-11 217777.77777777778 -1.0668034339239166e-10 217777.77777777778; -6.00076931582203e-11 122500.0 -1.200153863164406e-10 122500.0], [1.0, 1.0, 2.0, 2.0])

In [15]:
F

2×4 Array{Float64,2}:
 -5.33402e-11       2.17778e5  -1.0668e-10        2.17778e5
 -6.00077e-11  122500.0        -1.20015e-10  122500.0      

In [16]:
FFreqs

4-element Array{Float64,1}:
 1.0
 1.0
 2.0
 2.0

In [17]:
?designMatrixDM

search: designMatrixDM designMatrixRed designMatrixEnvelope



```
designMatrixDM(
    toas,
    freqs;
    nMode=30, 
    TSpan=Nothing, 
    fRef=1400.0,
    logFreq=false
)
```

Construct an $N_{toas} × 2N_{mode}$ dispersion measure (DM)-variation Fourier design matrix.  Current normalization expresses DM signal as a deviation [seconds] at fRef [MHz]. It is a special case of designMatrixChromatic with index=2.

# Arguments

  * `toas::Array`: vector of time of arrial series in seconds.
  * `freqs:Array`: radio frequencies of observations [MHz].
  * `nMode::Integer=30`: number of fourier coefficients to use.
  * `TSpan:Float64=Nothing`: option to some other Tspan.
  * `fRef:Float64=1400.0`: reference frequency [MHz].
  * `logFreq::Bool=false`: use log frequency spacing.

# Examples

```jldoctest
julia> toas = [1, 2]
julia> freqs = [3, 4]
julia> F, FFreqs = designMatrixDM(toas, freqs, nMode=2)
julia> F
2×4 Array{Float64,2}:
 -5.33402e-11       2.17778e5  -1.0668e-10        2.17778e5
 -6.00077e-11  122500.0        -1.20015e-10  122500.0 
julia> FFreqs
4-element Array{Float64,1}:
 1.0
 1.0
 2.0
 2.0
```

# See also

[`designMatrixRed`](@ref), [`designMatrixEnvelope`](@ref), [`designMatrixChromatic`](@ref), [`designMatrixEphemeris`](@ref)


# designMatrixEphemeris

In [18]:
toas = [1, 2]
pos = [3, 4, 5]
F, FFreqs = designMatrixEphemeris(toas, pos, nMode=2);

In [19]:
F

2×12 Array{Float64,2}:
 -7.34788e-16  -9.79717e-16  -1.22465e-15  …  -2.44929e-15  3.0  4.0  5.0
 -1.46958e-15  -1.95943e-15  -2.44929e-15     -4.89859e-15  3.0  4.0  5.0

In [20]:
FFreqs

12-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0

In [21]:
?designMatrixEphemeris

search: designMatrixEphemeris



```
designMatrixEphemeris(
    toas,
    pos;
    nMode=30, 
    TSpan=Nothing, 
    logFreq=false
)
```

Construct an $N_{toas} × 6N_{mode}$ ephemeris perturbation Fourier design matrix.  The matrix contains $6N_{mode}$ columns, ordered as by frequency first, Cartesian coordinate second:

$$
    sin(f0)[x], sin(f0)[y], sin(f0)[z], cos(f0)[x], cos(f0)[y], cos(f0)[z],\

    sin(f1)[x], sin(f1)[y], sin(f1)[z], cos(f1)[x], cos(f1)[y], cos(f1)[z],
    ...
$$

The corresponding frequency vector repeats every entry six times. This design matrix should be used with monopole_orf overlap function  and with a powerlaw that specifies components=6.

# Arguments

  * `toas::Array`: vector of time of arrial series in seconds.
  * `pos:Array`: radio frequencies of observations [MHz].
  * `nMode::Integer=30`: number of fourier coefficients to use.
  * `TSpan:Float64=Nothing`: option to some other Tspan.
  * `logFreq::Bool=false`: use log frequency spacing.

# Examples

```jldoctest
julia> toas = [1, 2]
julia> pos = [3, 4, 5]
julia> F, FFreqs = designMatrixEphemeris(toas, pos, nMode=2);
julia> F
2×12 Array{Float64,2}:
 -7.34788e-16  -9.79717e-16  -1.22465e-15  …  -2.44929e-15  3.0  4.0  5.0
 -1.46958e-15  -1.95943e-15  -2.44929e-15     -4.89859e-15  3.0  4.0  5.0
julia> FFreqs
12-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0
```

# See also

[`designMatrixRed`](@ref), [`designMatrixEnvelope`](@ref), [`designMatrixChromatic`](@ref), [`designMatrixDM`](@ref)
